/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    Banner: typeof import('./components/features/Banner.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ExpandingSearchBar: typeof import('./components/features/ExpandingSearchBar.vue')['default']
    HomePage: typeof import('./views/HomePage.vue')['default']
    LanguageSwitcher: typeof import('./components/features/LanguageSwitcher.vue')['default']
    NavigationBar: typeof import('./components/layout/NavigationBar.vue')['default']
    ProductCard: typeof import('./components/features/ProductCard.vue')['default']
    ProductGallery: typeof import('./components/features/ProductGallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultsPage: typeof import('./views/SearchResultsPage.vue')['default']
    ShoppingCartIcon: typeof import('./components/features/ShoppingCartIcon.vue')['default']
    ShoppingCartPopoverContent: typeof import('./components/features/ShoppingCartPopoverContent.vue')['default']
    TopNotification: typeof import('./components/layout/TopNotification.vue')['default']
  }
}
