/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutPage: typeof import('./views/AboutPage.vue')['default']
    AppDownloadPage: typeof import('./views/AppDownloadPage.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    Banner: typeof import('./components/features/Banner.vue')['default']
    CartPage: typeof import('./views/CartPage.vue')['default']
    CategoryPage: typeof import('./views/CategoryPage.vue')['default']
    CustomSearchBar: typeof import('./components/features/CustomSearchBar.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ExpandingSearchBar: typeof import('./components/features/ExpandingSearchBar.vue')['default']
    HealthSection: typeof import('./components/features/HealthSection.vue')['default']
    HomePage: typeof import('./views/HomePage.vue')['default']
    LanguageSwitcher: typeof import('./components/features/LanguageSwitcher.vue')['default']
    NavigationBar: typeof import('./components/layout/NavigationBar.vue')['default']
    NavItem: typeof import('./components/layout/NavItem.vue')['default']
    OurStoryPage: typeof import('./views/OurStoryPage.vue')['default']
    ProductCard: typeof import('./components/features/ProductCard.vue')['default']
    ProductGallery: typeof import('./components/features/ProductGallery.vue')['default']
    ProfilePage: typeof import('./views/ProfilePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPage: typeof import('./views/SearchPage.vue')['default']
    SearchResultsPage: typeof import('./views/SearchResultsPage.vue')['default']
    ShopAllPage: typeof import('./views/ShopAllPage.vue')['default']
    ShoppingCartIcon: typeof import('./components/features/ShoppingCartIcon.vue')['default']
    ShoppingCartPopoverContent: typeof import('./components/features/ShoppingCartPopoverContent.vue')['default']
    SubscriptionModal: typeof import('./components/features/SubscriptionModal.vue')['default']
    TopNotification: typeof import('./components/layout/TopNotification.vue')['default']
  }
}
